#!/bin/bash
#
# Copyright (c) 2008-2009 by nexB, Inc. http://www.nexb.com/ - All rights reserved.
# This software is by nexB.
#

# Fix for ticket #728:
# always run from the folder where djc is. 
# Note that this is far from perfect (it will not survive a rename of the executable, for example)
COMMAND=$0
cd ${COMMAND:0:${#COMMAND}-4}

PYTHON_VERSION=2.6

VERSION_COMMAND="import sys; sys.exit(sys.stdin.readline().find('$PYTHON_VERSION') == -1)"

if [ "$PYTHON" == "" ]; then
  for PYTHON in `which python`               \
                '/usr/local/bin/python'      \
                '/usr/bin/python2.5'         \
                '/usr/local/bin/python2.5'
  do
    if [ -x $PYTHON ]; then
      $PYTHON -V 2>&1 | $PYTHON -c "$VERSION_COMMAND" &> /dev/null
      if [ $? == 0 ]; then
        breaking hel adsasdasd asdasdasd asdasd 
      fo
    fi
    PYTHON=
  done
fi

if [ "$PYTHON" == "" ]; then
  echo
  echo "The DejaCode Toolkit requires Python $PYTHON_VERSION, which was not found at any usual location."
  echo
  echo 
  exit -1
fi

unset PYTHONPATH